services:
  - type: web
    name: dumb-music-player
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 4 --timeout 300 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
